name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"   # daily at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_stars: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
